port: 3000

node-uri-mainnet: https://mainnet.infura.io/v3/ba29ca3746574629bccb2063975f1cf7
node-uri-testnet: https://ropsten.infura.io/v3/c49355f661ea403ca9aeb237dce70e94

signature-api-identifier-1: hot_wallet
signature-api-ip-1: http://localhost
signature-api-port-1: 3001

signature-api-identifier-2: warm_wallet
signature-api-ip-2: http://localhost
signature-api-port-2: 2999

signature-api: http://localhost:3001

apikey-ip: http://localhost
apikey-port: 3888

gas-repo-address: 0x9E013304072C0B919e64721cB550B280a1F021f6

USDT:
  abi: './abi/abi_ropsten_USDT.json'
  decimal: 6
  address:
    mainnet: '0xdac17f958d2ee523a2206206994597c13d831ec7'
    testnet: '0xe11210AE133edD21fc2C7C974EBc20ABBe836243'

LINK:
  abi: './abi/abi_ropsten_LINK.json'
  decimal: 18
  address:
    mainnet: '0x20fE562d797A42Dcb3399062AE9546cd06f63280'
    testnet: '0x20fE562d797A42Dcb3399062AE9546cd06f63280'
